Models/ErrorViewModel.cs
using System;

namespace CEROK_WEBAPP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HastaModel.cs
using CEROK_WEBAPP.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CEROK_WEBAPP.Models
{
    public class HastaModel
    {
        public int hastaID { get; set; }
        public string tc { get; set; } = null!;
        public string sifre { get; set; } = null!;
        public string isim { get; set; } = null!;
        public string soyad { get; set; } = null!;
        public string cinsiyet { get; set; } = null!;
        public DateTime dogumTarihi { get; set; }
        public string telefonNo { get; set; } = null!;
        public string? email { get; set; }
        public string? kanGrubu { get; set; }
        public int? yas { get; set; }
        public int? boy { get; set; }
        public int? kilo { get; set; }



    }
}

Controllers/HastaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using CEROK_WEBAPP.Models;

namespace CEROK_WEBAPP.Controllers
{
    public class HastaController : Controller
    {
        
        public ActionResult HastaView()
        {
            IEnumerable<HastaModel> hastas = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7086/api/");

                //Called Member default GET All records  
                //GetAsync to send a GET request   
                // PutAsync to send a PUT request  
                var responseTask = client.GetAsync("hasta");
                responseTask.Wait();

                //To store result of web api response.   
                var result = responseTask.Result;

                //If success received   
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<HastaModel>>();
                    readTask.Wait();

                    hastas = readTask.Result;
                }
                else
                {
                    //Error response received   
                    hastas = Enumerable.Empty<HastaModel>();
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }

                return View(hastas);
            }

        }           
        }
}








   /* public class DoktorController : Controller
    {
        Uri baseAdress = new Uri ("https://localhost:7086");
        HttpClient httpClient;

        public DoktorController()
        {
            httpClient = new HttpClient();
            httpClient.BaseAddress = baseAdress;
        }
        public IActionResult DoktorView()
        {
            
            List<DoktorController> doktors = new List<DoktorController>();
            HttpResponseMessage response = httpClient.GetAsync(httpClient.BaseAddress+"/api/Doktor").Result;
            if(response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                doktors = JsonConvert.DeserializeObject<List<DoktorController>>(data);
            }
            return View(doktors);
        }
    }
}
   */

Controllers/HomeController.cs
using CEROK_WEBAPP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewEngines;


// project url : https://localhost:7086/swagger/index.html
namespace CEROK_WEBAPP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LoginView()
        {
            

            return View();
            
        }
        public IActionResult KayitSayfasi()
        {
           
            return View();


        }
     
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

Views/Hasta/HastaView.cshtml
@model IEnumerable<CEROK_WEBAPP.Models.HastaModel>

@{
    ViewData["Title"] = "HastaView";
}

<h1>HastaView</h1>
<head>
    <style type="text/css">
        body {
            background: #ffffff;
            font-size: 14px;
            font-family: Trebuchet MS;
        }
    </style>
</head>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.hastaID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sifre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.soyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cinsiyet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dogumTarihi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefonNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.kanGrubu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.yas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.boy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.kilo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.hastaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sifre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.soyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cinsiyet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dogumTarihi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefonNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kanGrubu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.yas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.boy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kilo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>
    <style type="text/css">
        body {
            background: #ffffff;
            font-size: 14px;
            font-family: Trebuchet MS;
        }
    </style>
</head>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/KayitSayfasi.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
    <html>
    <head>
        <title>Kullanıcı Kayıt Formu</title>
        <style type="text/css">
            body {
                background: #db9ce5;
                font-size: 14px;
                font-family: Trebuchet MS;
            }

            #kayitFormu {
                border-radius: 10px;
                background: #ffffff;
                width: 400px;
                margin: auto;
                margin-top: 40px;
                padding: 25px;
                text-align: center;
            }

            input, button {
                border-radius: 5px;
                border: none;
                width: 300px;
                height: 50px;
                margin: 20px 0px 20px 0px;
                background: rgba(240,240,240,.5);
                padding-left: 15px;
                font-style: italic;
            }

            .btn {
                background: #8bbeda;
                color: white;
            }

            h3 {
                color: #333;
                text-transform: uppercase;
                font-size: 20px;
            }
        </style>
    </head>
    <body>
        <div id="kayitFormu">
            <form action="kayityap.php" method="get">
                <h3>KULLANICI Kayıt Formu</h3>
                <input type="text" name="adiniz" placeholder="kullanıcı adı" required maxlength="6" />

                <input type="email" name="eposta" placeholder="eposta giriniz" required />

                <input type="password" name="parola" placeholder="şifrenizi giriniz" required pattern="[0-9a-zA-Z]{5}" />

                <input class="btn" type="submit" value="KAYIT OL" onclick="kayıtButonu" />
            </form>

        </div>


    </body>
</html>
</div>

Views/Home/LoginView.cshtml
@{
    ViewData["Title"] = "Merhaba";
}
<h1>@ViewData["Title"]</h1>
<head>
    <style type="text/css">
        body {
            background: #ffffff;
            font-size: 14px;
            font-family: Trebuchet MS;
        }
    </style>
</head>

<body>

    <div>
        <p>
            Sisteme kayıtlı değilseniz kayıt olmak için butona basınız.
            <input type="button" value="Kayıt Ol" onclick="location.href ='KayitSayfasi'" />
        </p>
    </div>

    <div class="text-center">

        <html>
        <head>
            <title>Lütfen Giriş Yapınız</title>
            <style type="text/css">
                body {
                    background: #db9ce5;
                    font-size: 14px;
                    font-family: Trebuchet MS;
                }

                #kayitFormu {
                    border-radius: 10px;
                    background: #ffffff;
                    width: 360px;
                    margin: auto;
                    margin-top: 20px;
                    padding: 15px;
                    text-align: center;
                }

                input, button {
                    border-radius: 5px;
                    border: none;
                    width: 300px;
                    height: 50px;
                    margin: 20px 0px 20px 0px;
                    background: rgba(240,240,240,.5);
                    padding-left: 15px;
                    font-style: italic;
                }

                .btn {
                    background: #8bbeda;
                    color: white;
                }

                h3 {
                    color: #333;
                    text-transform: uppercase;
                    font-size: 20px;
                }
            </style>

        </head>
</body>
<body>
    <div id="kayitFormu">
        <form action="kayityap.php" method="get">
            <h3>Sisteme Giriş Yapınız</h3>
            <input type="text" name="adiniz" placeholder="kullanıcı adı" required maxlength="6" />

            <input type="password" name="parola" placeholder="şifrenizi giriniz" required pattern="[0-9a-zA-Z]{5}" />

            <input name="GirisButonu" class="btn" type="button" value="Giriş Yap" onclick="location.href = 'HastaSayfasi'" />

        </form>

    </div>


</body>
    </html>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CEROK_WEBAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CEROK_WEBAPP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LoginView">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hasta" asp-action="HastaView">Hasta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>